### ISSUE TITLE
SDM Issue - Service worker will only run via https

### ISSUE THREAD

**Issue by kevzlou7979** [gwidgets/gwt-pwa-demo#1]
Hi,

I found out that SDM does not support HTTPS but also on Service worker the only way to work with this feature is only when running https.

Can you show us , how to run the simple project on Local.

Thanks,
Kevin

**Comment by kevzlou7979** [comment]
See attached screenshot
![test](https://cloud.githubusercontent.com/assets/3138071/20295499/42367106-ab40-11e6-93a3-c2994938f40c.gif)

**Comment by zak905** [comment]
Hi, 

You are right service workers work only in https, but http://localhost is also considered as secure by the sw, so you can replace 127.0.0.1 by localhost and it will work. Second, you need to edit the src/main/webapp/sw.js file to relpace the existing modules names with your gwt compiled modules file names. For example, here you can replace 1A07221213A47D5F8369817C9ECDDAE7 by your own mapping

```
//this is the safari mapping, you can add mappings for all the browsers
                        'pwademo/1A07221213A47D5F8369817C9ECDDAE7.cache.js',
// files created because of code spliting
                       'pwademo/deferredjs/1A07221213A47D5F8369817C9ECDDAE7/1.cache.js',
                       'pwademo/deferredjs/1A07221213A47D5F8369817C9ECDDAE7/2.cache.js',
                       'pwademo/deferredjs/1A07221213A47D5F8369817C9ECDDAE7/3.cache.js'
```

After service worker is activated, if you disable the network and refresh you will always see the dev mode pop up because GWT .js file is trying to query the code server for changes, the app would still work though 

![gwt-sdmpopup](https://cloud.githubusercontent.com/assets/6265563/20300954/b9c76afa-ab21-11e6-9705-8956987a5186.png)

If you want to test it in production, you can use Github pages or Heroku which provides support for https://

**Comment by kevzlou7979** [comment]
Thanks for this info will try this out on GMD.

**Comment by kevzlou7979** [comment]
Still does not work on my dev

Here's a screenshot
![image](https://cloud.githubusercontent.com/assets/3138071/23653154/7150844e-0366-11e7-8d66-e4c9b4aa841c.png)

Here's a screenshot for the cached files
![image](https://cloud.githubusercontent.com/assets/3138071/23656272/f4d97458-0373-11e7-8592-db05d2e4e5c1.png)

**Comment by zak905** [comment]
is the source code on github ?

**Comment by kevzlou7979** [comment]
Hi @zak905 ,

Here's the repository I made https://github.com/kevzlou7979/gwt-material-pwa

**Comment by zak905** [comment]
It's working for me. 
![pwa](https://cloud.githubusercontent.com/assets/6265563/23709555/22e4c7f2-041a-11e7-9ae5-199eb2a3a398.png)

You need to add the GWT specific mapping file (e.g 78420AAE3F91721E19BC13B2605182A5.cache.js) and not only the .nocache.js file. This is because the .nocache.js file will look for specific .cache.js depending on the browser ( see the initiator column in the picture). Unfortunately, the name of the file will only be known after compiling, so you will need to do it in two steps: gwt:compile and then take the name of the file and add it to the filesToCache in sw.js:
```
var filesToCache = [
    'index.html',
    'manifest.json',
    'sw.js',
    'GwtMaterialBasic/GwtMaterialBasic.nocache.js',
    'GwtMaterialBasic/css/overridecss.css',
    'GwtMaterialBasic/css/animation.css',
    'GwtMaterialBasic/css/material-icons.css',
    'GwtMaterialBasic/css/materialize.min.css',
    'GwtMaterialBasic/78420AAE3F91721E19BC13B2605182A5.cache.js'
];
```
and then package. 
This will only work in production not in devmode. This can be tedious, but this is the solution for now. I am trying to come up with a better solution ( maybe using some JsInterop).

**Comment by kevzlou7979** [comment]
Hi @zak905 Thanks for this I will try this out, I will try to have experiment on Service Worker also to have it in JSInterop.

**Comment by kevzlou7979** [comment]
I see a problem when you check offline checkbox under Application Tab and refresh the page. The SDM does not work or recompile.

![image](https://cloud.githubusercontent.com/assets/3138071/23737210/6f6ab836-04cc-11e7-875c-da3879af25bb.png)

**Comment by zak905** [comment]
That's normal. SDM script needs to query the code server after each refresh. Sw can only be used in production, it's better not to include it into dev mode. I am using a local jetty server to test, but you can use  even a web server like apache, or python's SimpleHttpServer, since the app has no server side.

**Comment by kevzlou7979** [comment]
We have implemented 3 more PWA Specific Features
1. Installable 
2. Service Worker
3. Push Notifications
Thanks for this ,  it helps us alot to build a GWT PWApp.

Source:
https://gwtmaterialdesign.github.io/gwt-material-demo/pwa
